version: "3.9"
services:
  backend:
    image: 'springboot-backend:latest'
    container_name: SpringBootSecurityJWT
    restart: always
    ports:
      - "80:2023"
    environment:
      SPRING_PROFILES_ACTIVE: main
      SERVER_PORT: 9797
      POSTGRES_DB: jdbc:postgresql://database:5432/postgres
      POSTGRES_USER: mukhammed
      POSTGRES_PASSWORD: mukhammed
  database:
    image: postgres:15
    restart: always
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mukhammed
      POSTGRES_PASSWORD: mukhammed
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: