spring:
    application:
        name: SpringBootSecurityJWT

    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5454/test
        username: postgres
        password: postgres

    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true

server:
    error:
        include-stacktrace: always
    port: 9790
app:
    jwt:
        secret: mukhammed.codes