spring:
    application:
        name: SpringBootSecurityJWT

    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5434/deployment
        username: postgres
        password: yiman

    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true

server:
    error:
        include-stacktrace: always
    port: 9797
app:
    jwt:
        secret: mukhammed.codes